ProgrammingContest/contest/contest/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from users.views import random_view

from home.views import HomePageView

from django.contrib.auth.decorators import login_required

# Base for all the urls, the app urls are included here
urlpatterns = [
    path('', HomePageView.as_view()),

    path('submission/', include('submission.urls')),

    path('home/', include('home.urls')),
    
    path('oracle/', include('oracle.urls')),

    path('login/', include('login.urls')),

    path('users/', include('users.urls')),

    path('contests/', include('contests.urls')),

    path('users/random/', random_view),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ProgrammingContest/contest/contests/urls.py
from django.urls import path

from django.contrib.auth.decorators import login_required

from .views import (
    ContestListView,
    ContestDetailView,
    ContestDeleteView,
    ContestCreateView,
    ContestUpdateView,
    ContestStartView,
    ContestStopView,
    ProblemDetailView,
    ContestSubmissionsListView,
    ContestScoreBoardView,
    ContestProblemCreateView,
    ContestSubmissionsForTeamView,
    ContestPauseView,
    ContestSubmissionDeleteView
)

from submission.views import SubmissionCreateView

app_name = 'contests'

#URLS in the contest/ link
urlpatterns = [
    path('', ContestListView.as_view(), name = 'contest-list'),
    path('<int:id>/', ContestDetailView.as_view(), name = 'contest-detail'),
    path('<int:id>/delete/', ContestDeleteView.as_view(), name = 'contest-delete'),
    path('create/', ContestCreateView.as_view(), name = 'contest-create'),
    path('<int:id>/update/', ContestUpdateView.as_view(), name = 'contest-update'),
    path('<int:id>/start/', ContestStartView.as_view(), name = 'contest-start'),
    path('<int:id>/stop/', ContestStopView.as_view(), name = 'contest-stop'),
    path('<int:id>/pause/', ContestPauseView.as_view(), name = 'contest-pause'),
    path('<int:id>/problem/<int:problem_id>/', ProblemDetailView.as_view(), name = 'problem-detail'),
    path('<int:id>/submissions/', ContestSubmissionsListView.as_view(), name = 'contest-submissions'),
    path('<int:id>/submissions/delete/', ContestSubmissionDeleteView, name = 'contest-submissions-delete'),
    path('<int:id>/problem/<int:problem_id>/submit/', SubmissionCreateView.as_view(), name = 'contest-submission-create'),
    path('<int:id>/scoreboard/', ContestScoreBoardView.as_view(), name = 'contest-scoreboard'),
    path('<int:id>/problems/create/', ContestProblemCreateView.as_view(), name = 'contest-problem-create'),
    path('<int:id>/submissions/<int:team_id>/', ContestSubmissionsForTeamView.as_view(), name = 'contest-team-submissions')
]

ProgrammingContest/contest/home/urls.py
from django.urls import path

app_name = 'home'

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name = 'homepage-view')
]

ProgrammingContest/contest/login/urls.py
from django.urls import path

from .views import (
    LoginPageView,
    LogoutView,
)

app_name = 'login'

urlpatterns = [
    path('', LoginPageView.as_view(), name='login-page'),
    path('logout', LogoutView.as_view(), name='logout-page'),
]

ProgrammingContest/contest/oracle/urls.py
from django.urls import path

from django.contrib.auth.decorators import login_required

from .views import (
    PostsListView,
    PostCreateView,
    PostDetailView,
    PostAnswerView,
    PostDeleteView
)

app_name = 'oracle'

urlpatterns = [
    path('', PostsListView.as_view(), name='posts-list'),
    path('create/', PostCreateView.as_view(), name = 'post-create'),
    path('<int:id>/', PostDetailView.as_view(), name = 'post-detail'),
    path('<int:id>/answer/', PostAnswerView.as_view(), name = 'post-answer'),
    path('<int:id>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
]

ProgrammingContest/contest/submission/urls.py
from django.urls import path

from django.contrib.auth.decorators import login_required

from .views import (
    SubmissionCreateView,
    SubmissionListView,
    SubmissionGradeView,
    SubmissionDownloadView
)

app_name = 'submission'

urlpatterns = [
    path('', SubmissionListView.as_view(), name='submission-list'),
    path('create/', SubmissionCreateView.as_view(), name = 'submission-create'),
    path('<int:id>/grade/', SubmissionGradeView.as_view(), name = 'submission-grade'),
    path('<int:id>/download/', SubmissionDownloadView.as_view(), name = 'submission-download'),
]

ProgrammingContest/contest/users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import(
    UserListView,
    UserDetailView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
)

app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name = 'user-list'),
    path('<int:id>/', UserDetailView.as_view(), name = 'user-detail'),
    path('create/', UserCreateView.as_view(), name = 'user-create'),
    path('<int:id>/update/', UserUpdateView.as_view(), name = 'user-update'),
    path('<int:id>/delete/', UserDeleteView.as_view(), name = 'user-delete'),
]

ProgrammingContest/contest/contests/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse

from django.views.generic import(
    CreateView, 
    DetailView, 
    ListView, 
    UpdateView, 
    DeleteView,
    TemplateView
)

from .forms import ContestModelForm, ContestUpdateForm, ProblemCreateForm

from .models import Contest, Problem

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from contest.decorators import class_view_decorator, admin_only_view, custom_login_required, admin_grader_only
from django.contrib import messages

import os, shutil
import datetime
from collections import OrderedDict

@class_view_decorator(custom_login_required)
class ContestProblemCreateView(CreateView):
    model = Problem
    template_name  = "contests/problem_create.html"
    form_class = ProblemCreateForm
    queryset = Problem.objects.all()

    def form_valid(self, form):
        id_ = self.kwargs.get("id")
        form.instance.contest = Contest.objects.get(id = id_)
        return super().form_valid(form)
    
    def get_success_url(self):
        id_ = self.kwargs.get("id")
        return (Contest.objects.get(id = id_).get_absolute_url())

@class_view_decorator(custom_login_required)
class ContestScoreBoardView(ListView):
    template_name = "contests/contest_scoreboard.html"

    def get_queryset(self):
        contest_id       = self.kwargs.get("id")
        current_contest     = Contest.objects.get(id = contest_id)
        from users.models import CustomUser
        teams = CustomUser.objects.filter(participatingIn = current_contest)
        
        return teams

    def get_team_problem_submission(self, team, problem):
        from submission.models import Submission
        return self.objects.get(submissionTeam = team, submissionProblem = problem)
        

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        contest_id       = self.kwargs.get("id")
        current_contest     = Contest.objects.get(id = contest_id)
        problem_list        = current_contest.contestproblems.all()

        from submission.models import Submission
        submissionList      = Submission.objects.filter(submissionProblem__in = problem_list)

        from users.models import CustomUser
        teams = CustomUser.objects.filter(participatingIn = current_contest)

        context['submission_list']  = submissionList
        context['problem_list']     = problem_list
        context['team_list']        = teams
        context['contest']          = current_contest
        score_data = {}

        # Creating a dictionary of dictionary that holds the latest submission for each problem, total sum, total correct submissions 
        for team in teams:
            score_data[team] = {}
            sum = 0
            correct_submissions = 0
            for problem in problem_list:
                submissions_of_problem_for_team = submissionList.filter(submissionTeam = team, submissionProblem = problem)
                if submissions_of_problem_for_team.count() > 0:
                    main_submission = submissions_of_problem_for_team.order_by('-subTouchTime').first()

                    if main_submission.submissionGrade == "pass":
                        correct_submissions += 1
                    score_data[team][problem] = main_submission
                    sum += main_submission.get_submission_score()
                
            score_data[team]["sum"] = sum
            score_data[team]["correct"] = correct_submissions
        
        # Storing the dictionary as data to be accessed in the template
        context['score_data'] = score_data
       
        # sorting the data for scores
        od = OrderedDict(sorted (score_data.items(), key = lambda kv:kv[1]["sum"], reverse=False))
        od = OrderedDict(sorted (score_data.items(), key = lambda kv:kv[1]["correct"], reverse=True))

        context['score_data'] = od

        remainingTime = current_contest.get_remaining_time()
        
        # closing the scoreboard if less than 30 minutes remaining
        if (remainingTime // 3600 > 0 or ((remainingTime // 60) % 60) >= 30 or (remainingTime == 0)): 
            scoreboard_active = True
        else:
            scoreboard_active = False
        context['active_status'] = scoreboard_active
        return context

@class_view_decorator(custom_login_required)
@class_view_decorator(admin_grader_only)
class ContestSubmissionsListView(ListView):
    template_name = "contests/contest_submissions.html"
    
    def get_queryset(self):
        from submission.models import Submission
        contest_id       = self.kwargs.get("id")
        current_contest     = Contest.objects.get(id = contest_id)
        problem_list        = current_contest.contestproblems.all()
        submissionList      = Submission.objects.filter(submissionProblem__in = problem_list)
        latestSubmissions   = []

        for eachuser in current_contest.contestants.all():
            submissions = submissionList.filter(submissionTeam = eachuser)
            for each_problem in problem_list:
                all_submissions = submissions.filter(submissionProblem = each_problem)
                if all_submissions.count() > 0:
                    main_submission = all_submissions.order_by('-subTouchTime').first()
                    latestSubmissions.append(main_submission)

        return latestSubmissions

# Normal view instead of class based view used
def ContestSubmissionDeleteView(request, id, *args, **kwargs):
    if request.method == "POST" and request.user.userType.lower() == "administrator":
        current_contest = Contest.objects.get(id = id)
        problem_list        = current_contest.contestproblems.all()

        from submission.models import Submission
        submissionList      = Submission.objects.filter(submissionProblem__in = problem_list)
        for each in submissionList:
            each.delete()
        from django.conf import settings
        media_root = settings.MEDIA_ROOT
        path = os.path.join(media_root,"submissions", current_contest.contestName)
       
        if os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)
        return redirect('../../../')

    current_contest = Contest.objects.get(id = id)
    context = {
        "object":current_contest
    }
    return render(request, "contests/contest_submissions_delete.html", context)

@class_view_decorator(custom_login_required)
class ContestSubmissionsForTeamView(ListView):
    template_name = "contests/contest_submissions_for_team.html"
    
    def get_queryset(self):
        from submission.models import Submission
        contest_id       = self.kwargs.get("id")
        team_id          = self.kwargs.get("team_id")
        current_contest     = Contest.objects.get(id = contest_id)
        problem_list        = current_contest.contestproblems.all()

        submissionList      = Submission.objects.filter(submissionProblem__in = problem_list)
        from users.models import CustomUser

        teamSubmissionList  = submissionList.filter(submissionTeam = CustomUser.objects.get(id = team_id))
        return teamSubmissionList

@class_view_decorator(custom_login_required)
class ProblemDetailView(DetailView):
    template_name = "contests/contest_problem_detail.html"

    def get_queryset(self):
        id_     = self.kwargs.get("id")
        print(id_)
        currObj = Contest.objects.get(id = id_) 
        return currObj.contestproblems.all()
    
    def get_object(self):
        id_problem = self.kwargs.get("problem_id")
        id_        = self.kwargs.get("id")

        currentobj = Contest.objects.get(id = id_)

        currObj    = currentobj.contestproblems.get(id = id_problem)
        return currObj
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        id_problem = self.kwargs.get("problem_id")

        from submission.models import Submission
        qs = Submission.objects.filter(submissionTeam = self.request.user, submissionProblem = Problem.objects.get(id = id_problem))
        
        if qs.exists:
            for ins in qs:
                currSubmission = ins
                context['currSubmission'] = currSubmission
        
        
        return context

@class_view_decorator(custom_login_required)
class ContestListView(ListView):
    template_name = "contests/contest_list.html"


    def get_queryset(self):
        if(self.request.user.userType.lower() == "team"):
            return Contest.objects.all().filter(contestants = self.request.user)
        else:
            return Contest.objects.all()
            

@class_view_decorator(custom_login_required)
class ContestStartView(TemplateView):
    def get(self, request, *args, **kwargs):
        id_ = self.kwargs.get("id")
        if Contest.objects.get(id = id_).isRunning == False:
            if(Contest.objects.get(id = id_).isPaused == True):  
                messages.success(request, 'Contest Resumed')
            else:
                messages.success(request, 'Contest Successfully Started')
            Contest.objects.filter(id = id_).update(isRunning = True)
            currentTime = datetime.datetime.now()
            print("Current and Start Time = ", currentTime)
            Contest.objects.filter(id = id_).update(startTime = currentTime)
        else:
            messages.success(request, 'Contest already running, Cannot start again')
        return ContestListView.as_view()(self.request)    

@class_view_decorator(custom_login_required)
class ContestPauseView(TemplateView):
    def get(self, request, *args, **kwargs):
        id_ = self.kwargs.get("id")
        if Contest.objects.get(id = id_).isRunning == True:

            print('Time remaining', Contest.objects.get(id = id_).get_remaining_time())

ProgrammingContest/contest/contest/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>UE ACM Programming Contest</title>
</head>

<body>
    {% include 'navbar.html' %}

    {% if messages %}
    {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block content %} 

        replace me
    {% endblock %}    
</body>
{% load static %}

</html>

ProgrammingContest/contest/contest/templates/denied.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'css/style_detail.css' %}" />

<h1>Your user group does not have access to this page.</h1>
<h2>Ask the administrator for more details</h2>

{% endblock %}

ProgrammingContest/contest/contest/templates/navbar.html
{% load static %}
<nav>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'css/navbar_style.css' %}" />
    <div id = "menu">
        <ul>
            <li id = "user">
            {% if request.user.userName != None and request.user.userName != "" %}
                        Current User: {{ request.user.userName }}
                    {% else %}
                        Current User: No User Logged In
            {% endif %}
            </li>
            <li><img src = "{% static 'logo/UElogo.jpg' %}" class = "logo1"/></li>
            <li><img src = "{% static 'logo/ACMlogo.png' %}" class = "logo"/></li>
            <li class="{% ifequal request.path '/home/'%} active {% endifequal%}">
                <a href="{% url 'home:homepage-view' %}"> Homepage</a>
            </li>

            <li class="{% if 'contests' in request.build_absolute_uri %} active {% endif%}">
                <a href="{% url 'contests:contest-list' %}"> Contests </a>
            </li>
            <li class="{% if 'users' in request.build_absolute_uri %} active {% endif%}">
                <a href="{% url 'users:user-list' %}"> Users </a>
            </li>
            <li class="{% ifequal request.path '/oracle/'%} active {% endifequal%}">
                <a href="{% url 'oracle:posts-list' %}"> Oracle </a>
            </li>

            <li class="{% ifequal request.path '/submission/'%} active {% endifequal%}">
                <a href="{% url 'submission:submission-list' %}"> Submissions </a>
            </li>


            <li style = "float:right"><a href="{% url 'login:logout-page' %}"> Logout </a></li>
            <li class="{% ifequal request.path '/login/'%} active {% endifequal%}"  style = "float:right">
                <a href="{% url 'login:login-page' %}"> Login </a>
            </li>
        </ul>
    </div>
</nav>

ProgrammingContest/contest/contest/templates/random_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .samplemenu ul{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%w, -50%);
        margin: 0;
        padding:0;
        display: flex;
    }

        .samplemenu ul li{
            list-style: none;

        }
        .samplemenu ul li a{
            position: relative;
            display: block;
            padding: 10px 20px;
            text-decoration: none;
            text-transform: uppercase;
            font-weight:
            bold;
        }

        .samplemenu ul li.active a{
            background-color: black;
        }

    </style>
</head>
<body>
    <div class = "samplemenu">
        <ul>
            <li class = "active"><a href = "#somewhere">Somewhere</a></li>
            <li><a href = "#somewhere1">Somewhere</a></li>
            <li><a href = "#somewhere2">Somewhere</a></li>
            <li><a href = "#somewhere3">Somewhere</a></li>
            <li><a href = "#somewhere4">Somewhere</a></li>
            <li><a href = "#somewhere5">Somewhere</a></li>
            <li><a href = "#somewhere6">Somewhere</a></li>
            <li><a href = "#somewhere7">Somewhere</a></li>
        </ul>
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="crossorigin="anonymous"></script>
        
        <script type = "text/javascript">
            $(document).on('click', 'ul li', function(){
                $(this).addClass('active').siblings().removeClass('active')
            })
        </script>
    </div>
</body>
</html>